(function(){
'use strict';
const $=id=>document.getElementById(id);
const clone=value=>JSON.parse(JSON.stringify(value));
const defaults={
  brief:{title:'Reimagining the ski pole for more effective use',purpose:'Use the unused space inside a ski pole to combine useful tools, interchangeable components and skiing feedback.',impact:'Create a useful product for skiers, reduce plastic waste, and learn how physical components and AI can work together.',question:'How might I reimagine the ski pole to reduce environmental impact, help skiers improve, and allow them to carry less gear?',steps:'Create success criteria and a materials list. Contact Jeremy. Research basket attachment systems, recycled plastic, sensors and AI coaching.'},
  materials:[{id:1,name:'Bamboo shaft',qty:'2 lengths',purpose:'Main pole body',status:'Needed',url:''},{id:2,name:'Recycled HDPE sheet',qty:'1 sheet',purpose:'Prototype basket',status:'Needed',url:''},{id:3,name:'Ski-pole ferrule and tip',qty:'1 set',purpose:'Lower pole connection',status:'Needed',url:''}],
  kwl:{know:['A ski pole needs a handle, strong shaft, basket and tip.','A recycled-plastic basket can be prototyped from a flat sheet.'],want:['How can baskets be quickly swapped?','How can sensors give useful skiing feedback?'],learnt:[]},
  tasks:[{id:11,text:'Research current ski-pole basket connectors',stage:'Research'},{id:12,text:'Contact Jeremy',stage:'Research'},{id:13,text:'Prototype a recycled-plastic basket',stage:'Prototype'}],
  sources:[],events:[]
};
let state;let monthCursor=new Date();
function load(){try{const raw=JSON.parse(localStorage.getItem('skiPoleOS')||'null');if(!raw)return clone(defaults);return{brief:{...defaults.brief,...(raw.brief||{})},materials:Array.isArray(raw.materials)?raw.materials.map(m=>({...m,url:m.url||''})):clone(defaults.materials),kwl:{know:raw.kwl?.know||clone(defaults.kwl.know),want:raw.kwl?.want||clone(defaults.kwl.want),learnt:raw.kwl?.learnt||[]},tasks:Array.isArray(raw.tasks)?raw.tasks:clone(defaults.tasks),sources:Array.isArray(raw.sources)?raw.sources:[],events:Array.isArray(raw.events)?raw.events:[]}}catch(error){console.error(error);return clone(defaults)}}
function save(){localStorage.setItem('skiPoleOS',JSON.stringify(state));renderAll()}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(value){const raw=String(value||'').trim();if(!raw)return'';const candidate=/^https?:\/\//i.test(raw)?raw:`https://${raw}`;try{const parsed=new URL(candidate);return/^https?:$/.test(parsed.protocol)?parsed.href:''}catch(error){return''}}
function id(){return Date.now()+Math.floor(Math.random()*10000)}
function iso(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function showEditor(editorId,show=true){$(editorId).hidden=!show;if(show)$(editorId).scrollIntoView({behavior:'smooth',block:'nearest'})}
function initNav(){const tabs=[['overview','Overview'],['brief','Project brief'],['materials','Materials'],['kwl','KWL'],['tasks','Tasks'],['sources','Sources'],['calendar','Calendar'],['ai','Project AI']];$('nav').innerHTML=tabs.map((tab,index)=>`<button type="button" class="${index===0?'active':''}" data-page="${tab[0]}">${tab[1]}</button>`).join('')}
function renderBrief(){const b=state.brief;$('briefView').innerHTML=`<article class="card"><h2>${esc(b.title)}</h2><p><strong>Purpose</strong><br>${esc(b.purpose)}</p><p><strong>Impact</strong><br>${esc(b.impact)}</p></article><article class="card"><p><strong>Driving question</strong><br>${esc(b.question)}</p><p><strong>First steps</strong><br>${esc(b.steps)}</p></article>`}
function materialRecord(m){const url=safeUrl(m.url);return`<article class="record"><div class="record-main"><strong>${esc(m.name)}</strong><p>${esc(m.qty||'No quantity')} · ${esc(m.purpose||'No purpose')}</p><span class="badge">${esc(m.status||'Needed')}</span>${url?`<a class="material-link" href="${esc(url)}" target="_blank" rel="noopener">Open material link ↗</a>`:''}</div><div class="record-actions"><button type="button" class="icon-button" data-edit-material="${m.id}" aria-label="Edit ${esc(m.name)}">✎</button><button type="button" class="icon-button" data-delete-material="${m.id}" aria-label="Delete ${esc(m.name)}">×</button></div></article>`}
function renderMaterials(){$('materialList').innerHTML=state.materials.length?state.materials.map(materialRecord).join(''):'<div class="empty">No materials yet. Click “Add material”.</div>'}
function renderKWL(){const names={know:'Know',want:'Want to know',learnt:'Learnt'};$('kwlColumns').innerHTML=['know','want','learnt'].map(kind=>`<article class="card"><div class="column-head"><h2>${names[kind]}</h2><button type="button" class="small-add" data-open-kwl="${kind}">+ Add</button></div><div id="${kind}Add" class="kwl-add" hidden><input id="${kind}New" placeholder="Type your note"><div class="editor-actions"><button type="button" class="secondary" data-close-kwl="${kind}">Cancel</button><button type="button" class="primary" data-save-kwl="${kind}">Save</button></div></div><div class="simple-list">${state.kwl[kind].length?state.kwl[kind].map((text,index)=>`<div class="record"><div class="record-main"><p>${esc(text)}</p></div><div class="record-actions"><button type="button" class="icon-button" data-edit-kwl="${kind}:${index}" aria-label="Edit note">✎</button><button type="button" class="icon-button" data-delete-kwl="${kind}:${index}" aria-label="Delete note">×</button></div></div>`).join(''):'<div class="empty">Nothing here yet.</div>'}</div></article>`).join('')}
function renderTasks(){$('taskList').innerHTML=state.tasks.length?state.tasks.map(t=>`<article class="record"><div class="record-main"><strong>${esc(t.text)}</strong><br><span class="badge">${esc(t.stage)}</span></div><div class="record-actions"><button type="button" class="icon-button" data-edit-task="${t.id}" aria-label="Edit task">✎</button><button type="button" class="icon-button" data-delete-task="${t.id}" aria-label="Delete task">×</button></div></article>`).join(''):'<div class="empty">No tasks yet. Click “Add task”.</div>'}
function renderSources(){$('sourceList').innerHTML=state.sources.length?state.sources.map(s=>`<article class="record"><div class="record-main"><strong>${esc(s.title)}</strong><p>${esc(s.claim||'No note added.')}</p>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener">Open source</a>`:''}</div><div class="record-actions"><button type="button" class="icon-button" data-edit-source="${s.id}" aria-label="Edit source">✎</button><button type="button" class="icon-button" data-delete-source="${s.id}" aria-label="Delete source">×</button></div></article>`).join(''):'<div class="empty">No sources yet. Click “Add source”.</div>'}
function renderCalendar(){const first=new Date(monthCursor.getFullYear(),monthCursor.getMonth(),1),offset=(first.getDay()+6)%7,start=new Date(first);start.setDate(first.getDate()-offset);const today=iso(new Date());$('monthLabel').textContent=monthCursor.toLocaleDateString('en-NZ',{month:'long',year:'numeric'});$('calendarGrid').innerHTML='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const date=iso(d),events=state.events.filter(e=>e.date===date),button=document.createElement('button');button.type='button';button.className=`day ${d.getMonth()!==monthCursor.getMonth()?'outside ':''}${date===today?'today':''}`;button.dataset.pickDate=date;button.innerHTML=`<strong>${d.getDate()}</strong>${events.map(e=>`<span class="event-chip">${esc(e.time||'')} ${esc(e.title)}</span>`).join('')}`;$('calendarGrid').appendChild(button)}const upcoming=state.events.filter(e=>e.date>=today).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||''))).slice(0,12);$('upcomingList').innerHTML=upcoming.length?upcoming.map(e=>`<article class="record"><div class="record-main"><strong>${esc(e.title)}</strong><p>${esc(e.date)} ${esc(e.time||'')} · ${esc(e.type)}</p></div><div class="record-actions"><button type="button" class="icon-button" data-edit-event="${e.id}" aria-label="Edit event">✎</button><button type="button" class="icon-button" data-delete-event="${e.id}" aria-label="Delete event">×</button></div></article>`).join(''):'<div class="empty">No upcoming events.</div>'}
function renderAll(){renderBrief();renderMaterials();renderKWL();renderTasks();renderSources();renderCalendar();$('metricMaterials').textContent=state.materials.length;$('metricTasks').textContent=state.tasks.length;$('metricEvents').textContent=state.events.length}
function openBrief(){const b=state.brief;$('briefTitle').value=b.title;$('briefPurpose').value=b.purpose;$('briefImpact').value=b.impact;$('briefQuestion').value=b.question;$('briefSteps').value=b.steps;showEditor('briefEditor')}
function openMaterial(item=null){$('materialEditorTitle').textContent=item?'Edit material':'Add material';$('materialEditId').value=item?.id||'';$('materialName').value=item?.name||'';$('materialQty').value=item?.qty||'';$('materialPurpose').value=item?.purpose||'';$('materialStatus').value=item?.status||'Needed';$('materialUrl').value=item?.url||'';showEditor('materialEditor')}
function openTask(item=null){$('taskEditorTitle').textContent=item?'Edit task':'Add task';$('taskEditId').value=item?.id||'';$('taskText').value=item?.text||'';$('taskStage').value=item?.stage||'Research';showEditor('taskEditor')}
function openSource(item=null){$('sourceEditorTitle').textContent=item?'Edit source':'Add source';$('sourceEditId').value=item?.id||'';$('sourceTitle').value=item?.title||'';$('sourceUrl').value=item?.url||'';$('sourceClaim').value=item?.claim||'';showEditor('sourceEditor')}
function openEvent(item=null,date=''){const today=iso(new Date());$('eventEditorTitle').textContent=item?'Edit event':'Add event';$('eventEditId').value=item?.id||'';$('eventTitle').value=item?.title||'';$('eventDate').value=item?.date||date||today;$('eventTime').value=item?.time||'';$('eventType').value=item?.type||'General';showEditor('eventEditor')}
function handleClick(event){const target=event.target.closest('button');if(!target)return;const action=target.dataset.action;if(target.dataset.page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('[data-page]').forEach(b=>b.classList.remove('active'));$(target.dataset.page).classList.add('active');target.classList.add('active');return}
if(action==='edit-brief')return openBrief();if(action==='cancel-brief')return showEditor('briefEditor',false);if(action==='save-brief'){state.brief={title:$('briefTitle').value.trim(),purpose:$('briefPurpose').value.trim(),impact:$('briefImpact').value.trim(),question:$('briefQuestion').value.trim(),steps:$('briefSteps').value.trim()};showEditor('briefEditor',false);return save()}
if(action==='open-add-material')return openMaterial();if(action==='close-material-editor')return showEditor('materialEditor',false);if(action==='save-material'){const name=$('materialName').value.trim();if(!name)return alert('Please add a material name.');const editId=$('materialEditId').value;const enteredUrl=$('materialUrl').value.trim();const data={name,qty:$('materialQty').value.trim(),purpose:$('materialPurpose').value.trim(),status:$('materialStatus').value,url:enteredUrl};if(enteredUrl&&!safeUrl(enteredUrl))return alert('Please enter a valid web link.');if(editId){const item=state.materials.find(x=>String(x.id)===editId);if(item)Object.assign(item,data)}else state.materials.push({id:id(),...data});showEditor('materialEditor',false);return save()}
if(target.dataset.editMaterial){const item=state.materials.find(x=>String(x.id)===target.dataset.editMaterial);if(item)return openMaterial(item)}if(target.dataset.deleteMaterial){state.materials=state.materials.filter(x=>String(x.id)!==target.dataset.deleteMaterial);return save()}
if(target.dataset.openKwl){$(target.dataset.openKwl+'Add').hidden=false;$(target.dataset.openKwl+'New').focus();return}if(target.dataset.closeKwl){$(target.dataset.closeKwl+'Add').hidden=true;return}if(target.dataset.saveKwl){const kind=target.dataset.saveKwl,input=$(kind+'New'),value=input.value.trim();if(value){state.kwl[kind].push(value);return save()}return}if(target.dataset.editKwl){const[kind,indexText]=target.dataset.editKwl.split(':'),index=Number(indexText),current=state.kwl[kind][index],next=prompt('Edit this note:',current);if(next!==null&&next.trim()){state.kwl[kind][index]=next.trim();return save()}}if(target.dataset.deleteKwl){const[kind,indexText]=target.dataset.deleteKwl.split(':');state.kwl[kind].splice(Number(indexText),1);return save()}
if(action==='open-add-task')return openTask();if(action==='close-task-editor')return showEditor('taskEditor',false);if(action==='save-task'){const text=$('taskText').value.trim();if(!text)return alert('Please add a task.');const editId=$('taskEditId').value,data={text,stage:$('taskStage').value};if(editId){const item=state.tasks.find(x=>String(x.id)===editId);if(item)Object.assign(item,data)}else state.tasks.push({id:id(),...data});showEditor('taskEditor',false);return save()}if(target.dataset.editTask){const item=state.tasks.find(x=>String(x.id)===target.dataset.editTask);if(item)return openTask(item)}if(target.dataset.deleteTask){state.tasks=state.tasks.filter(x=>String(x.id)!==target.dataset.deleteTask);return save()}
if(action==='open-add-source')return openSource();if(action==='close-source-editor')return showEditor('sourceEditor',false);if(action==='save-source'){const title=$('sourceTitle').value.trim();if(!title)return alert('Please add a source title.');const editId=$('sourceEditId').value,data={title,url:$('sourceUrl').value.trim(),claim:$('sourceClaim').value.trim()};if(editId){const item=state.sources.find(x=>String(x.id)===editId);if(item)Object.assign(item,data)}else state.sources.push({id:id(),...data});showEditor('sourceEditor',false);return save()}if(target.dataset.editSource){const item=state.sources.find(x=>String(x.id)===target.dataset.editSource);if(item)return openSource(item)}if(target.dataset.deleteSource){state.sources=state.sources.filter(x=>String(x.id)!==target.dataset.deleteSource);return save()}
if(action==='open-add-event')return openEvent();if(action==='close-event-editor')return showEditor('eventEditor',false);if(action==='save-event'){const title=$('eventTitle').value.trim(),date=$('eventDate').value;if(!title||!date)return alert('Please add an event title and date.');const editId=$('eventEditId').value,data={title,date,time:$('eventTime').value,type:$('eventType').value};if(editId){const item=state.events.find(x=>String(x.id)===editId);if(item)Object.assign(item,data)}else state.events.push({id:id(),...data});monthCursor=new Date(date+'T12:00:00');showEditor('eventEditor',false);return save()}if(target.dataset.editEvent){const item=state.events.find(x=>String(x.id)===target.dataset.editEvent);if(item)return openEvent(item)}if(target.dataset.deleteEvent){state.events=state.events.filter(x=>String(x.id)!==target.dataset.deleteEvent);return save()}if(target.dataset.pickDate)return openEvent(null,target.dataset.pickDate)}
function init(){state=load();initNav();document.addEventListener('click',handleClick);$('previousMonth').addEventListener('click',()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderCalendar()});$('nextMonth').addEventListener('click',()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderCalendar()});$('poleImage').addEventListener('error',()=>{$('poleImage').hidden=true;$('imageFallback').hidden=false});window.ProjectOS={getState:()=>state,save,makeId:id,localISO:iso,setMonth:d=>{monthCursor=new Date(d.getFullYear(),d.getMonth(),1)},renderAll};renderAll();window.dispatchEvent(new Event('ProjectOSReady'))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
