(function(){
'use strict';
const $=id=>document.getElementById(id);const api=window.ProjectOS;
function addBubble(text,type=''){const box=document.createElement('div');box.className=`bubble ${type}`;box.textContent=text;$('aiChat').appendChild(box);$('aiChat').scrollTop=$('aiChat').scrollHeight}
function nextWeekday(day,forceNext){const d=new Date(),diffBase=(day-d.getDay()+7)%7;d.setDate(d.getDate()+(diffBase===0&&forceNext?7:diffBase));return d}
function parseDate(text){const s=text.toLowerCase(),now=new Date();if(s.includes('day after tomorrow')){const d=new Date(now);d.setDate(d.getDate()+2);return d}if(s.includes('tomorrow')){const d=new Date(now);d.setDate(d.getDate()+1);return d}if(s.includes('today'))return now;let m=s.match(/\b(20\d{2})[-/](\d{1,2})[-/](\d{1,2})\b/);if(m)return new Date(+m[1],+m[2]-1,+m[3]);const days=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];for(let i=0;i<days.length;i++){if(s.includes('next '+days[i]))return nextWeekday(i,true);if(new RegExp(`(?:this\\s+|on\\s+|for\\s+|by\\s+)?${days[i]}\\b`).test(s))return nextWeekday(i,false)}const months=['january','february','march','april','may','june','july','august','september','october','november','december'];m=s.match(new RegExp(`(\\d{1,2})(?:st|nd|rd|th)?(?:\\s+of)?\\s+(${months.join('|')})(?:\\s+(20\\d{2}))?`));if(m){let year=+(m[3]||now.getFullYear()),d=new Date(year,months.indexOf(m[2]),+m[1]);if(!m[3]&&d<new Date(now.getFullYear(),now.getMonth(),now.getDate()))d.setFullYear(year+1);return d}return null}
function parseTime(text){let m=text.toLowerCase().match(/\b(?:at\s*)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/);if(m){let h=+m[1],min=m[2]||'00';if(m[3]==='pm'&&h<12)h+=12;if(m[3]==='am'&&h===12)h=0;return`${String(h).padStart(2,'0')}:${min}`}m=text.match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:''}
function inferEventType(text){const s=text.toLowerCase();if(/deadline|due|submit|finish/.test(s))return'Deadline';if(/contact|call|meet|jeremy/.test(s))return'Meeting';if(/test|trial|measure/.test(s))return'Testing';if(/build|make|prototype|mould|mold|laser/.test(s))return'Build';return'General'}
function cleanEventTitle(text){return text.replace(/\b(could you|can you|please|add|schedule|create|put|book|remind me|calendar|event)\b/gi,' ').replace(/\b(today|tomorrow|day after tomorrow|next\s+\w+|this\s+\w+|monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/gi,' ').replace(/\b(?:at\s*)?\d{1,2}(?::\d{2})?\s*(?:am|pm)\b/gi,' ').replace(/\b20\d{2}[-/]\d{1,2}[-/]\d{1,2}\b/g,' ').replace(/\s+/g,' ').trim().replace(/^(for|on|by|to)\s+/i,'')||'Project event'}
function summary(state){return`Your project has ${state.materials.length} materials, ${state.tasks.length} tasks, ${state.sources.length} sources and ${state.events.length} calendar events. The driving question is: ${state.brief.question}`}
function process(){
  const input=$('aiInput'),q=input.value.trim();if(!q)return;addBubble(q,'user');input.value='';const state=api.getState(),s=q.toLowerCase();
  const materialMatch=q.match(/(?:add|put)\s+(.+?)\s+(?:to|in)\s+(?:the\s+)?materials?/i);
  if(materialMatch){let name=materialMatch[1].trim().replace(/^\d+\s*/,'');const qtyMatch=materialMatch[1].match(/^([\w.-]+)\s+/);state.materials.push({id:api.makeId(),name,qty:qtyMatch?qtyMatch[1]:'1',purpose:'Added by Project AI',status:'Needed'});api.save();addBubble(`Added “${name}” to Materials.`,'success');return}
  if(/mark .+ (?:as )?(purchased|ordered|have it|tested)/i.test(q)){const m=q.match(/mark\s+(.+?)\s+(?:as\s+)?(purchased|ordered|have it|tested)/i),item=state.materials.find(x=>x.name.toLowerCase().includes(m[1].trim().toLowerCase()));if(item){item.status=m[2].toLowerCase()==='purchased'?'Have it':m[2][0].toUpperCase()+m[2].slice(1);api.save();addBubble(`Updated ${item.name} to “${item.status}”.`,'success')}else addBubble('I could not find that material.');return}
  const taskMatch=q.match(/(?:add|create)\s+(.+?)\s+(?:to|in)\s+(?:the\s+)?tasks?/i);
  if(taskMatch){state.tasks.push({id:api.makeId(),text:taskMatch[1].trim(),stage:/prototype|build/i.test(q)?'Prototype':/test/i.test(q)?'Test':'Research'});api.save();addBubble(`Added the task “${taskMatch[1].trim()}”.`,'success');return}
  const date=parseDate(q),eventIntent=/(schedule|calendar|event|remind|contact|call|meet|deadline|session|test|prototype)/i.test(q);
  if(eventIntent&&date){const event={id:api.makeId(),title:cleanEventTitle(q),date:api.localISO(date),time:parseTime(q),type:inferEventType(q)};state.events.push(event);api.setMonth(date);api.save();addBubble(`Added “${event.title}” for ${date.toLocaleDateString('en-NZ',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}${event.time?' at '+event.time:''}.`,'success');return}
  if(eventIntent&&!date){addBubble('I understood the event but need a date, such as Monday, tomorrow, 14 August, or 2026-08-14.');return}
  let kwl=q.match(/add\s+(?:that\s+)?i\s+learnt\s+(.+)/i);if(kwl){state.kwl.learnt.push(kwl[1].trim());api.save();addBubble('Added that to Learnt.','success');return}
  kwl=q.match(/add\s+(?:that\s+)?i\s+know\s+(.+)/i);if(kwl){state.kwl.know.push(kwl[1].trim());api.save();addBubble('Added that to Know.','success');return}
  kwl=q.match(/add\s+(?:the question\s+)?(.+?)\s+to\s+(?:want to know|want)/i);if(kwl){state.kwl.want.push(kwl[1].trim());api.save();addBubble('Added that to Want to know.','success');return}
  const brief=q.match(/set\s+(purpose|impact|question|first steps|steps|title)\s+to\s+(.+)/i);if(brief){const map={'first steps':'steps',steps:'steps',purpose:'purpose',impact:'impact',question:'question',title:'title'},key=map[brief[1].toLowerCase()];state.brief[key]=brief[2].trim();api.save();addBubble(`Updated the project ${brief[1].toLowerCase()}.`,'success');return}
  if(/summari[sz]e|project summary/.test(s)){addBubble(summary(state));return}
  if(/what materials|list materials/.test(s)){addBubble(state.materials.length?state.materials.map(m=>`${m.name} (${m.qty||'1'}, ${m.status})`).join('; '):'No materials are saved.');return}
  if(/what tasks|list tasks/.test(s)){addBubble(state.tasks.length?state.tasks.map(t=>`${t.text} [${t.stage}]`).join('; '):'No tasks are saved.');return}
  if(/what events|calendar/.test(s)){addBubble(state.events.length?state.events.map(e=>`${e.date}: ${e.title}`).join('; '):'No events are saved.');return}
  addBubble('I can change Materials, Tasks, KWL notes, the project brief and Calendar. Try a command from the examples panel.');
}
$('sendAI').addEventListener('click',process);$('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')process()});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{$('aiInput').value=b.dataset.prompt;process()}));
})();
